version: "~> 1.0"
language: android
jdk:
- openjdk11
dist: xenial

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - "/home/travis/.rvm/"

before_install:
- openssl aes-256-cbc -K $encrypted_711dc5014a8e_key -iv $encrypted_711dc5014a8e_iv
  -in keystore.jks.enc -out keystore.jks -d
- rvm install 2.6.5
- gem install fastlane
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-29
  - extra-google-google_play_services
before_script: cd project
script: "./build_on_travis.sh"
deploy:
  provider: releases
  api_key:
    secure: GmSq8D3Uxuyy1ZxNgB4OaHePJLaDp9B1qNLhZQ4enhl5f0KA4quJaiTfmxu7pjXZs1ga093J+PG2MNAPBoEqUzGCUNxLKPnxjtce10tFG/e+V7k4AOqtv/ekXK/tmPwYQOmSBh7fRRfTuivqRTEyqtJ/XRKScJU7muTxBGcTnr1ppKFMXkulHidaSrLng1qZdH8HNk4dDL6VEnCK1XAdJcDq/fJQHPYJMXPpvoKTz+bAdZ+XegGpOZRAUiGHCrEQcaYMSv/6JWZB1ZWAUwPmMbUO2nNuOtoGvimSDHVa6gcppStvfjM7NhH93uzisSsBdqOonHlj33fjuBchhwTGZvxj4huWCW//vOIpEmv2B8e+FzowfzEyXJIC0KUDoys3PVK5WucgkxpIkja2EAxYH5gtktYPLe0EXu/VyEvfFiiZi1ZgUU86J8ibW3AyUsOtvhpocnnJ24YvGrfL1U1EqTwfONHHosl6DklYq/yhK0FmWrf7sNRXtwiCGftPSdsngP7Hp8bn14WENv3xKsxQQ6mGasc2OxJmbPR8uw+lwSjPC1VOQ0QtPr9lyTqqqumPDoOBxqmnOKJEufsYARt0wkqV/2/g+1C5EaZzCu2EYce8cGF3IsrcUIG09AHr/ytecrvP4ISclwftxrgkCtu7FlXT0eJrCgOnjdDIGJab7ho=
  file: app/build/outputs/apk/release/app-release.apk
  draft: true
  skip_cleanup: true
  on:
    repo: owntracks/android
    tags: true
